//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_Web.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACI_OrdenAtencion
    {
        public ACI_OrdenAtencion()
        {
            this.ACI_Chip_OrdenAtencion = new HashSet<ACI_Chip_OrdenAtencion>();
        }
    
        public int idOrdenAtencion { get; set; }
        public int idPaciente { get; set; }
        public System.DateTime fechaOrdenAtencion { get; set; }
        public string observaciones { get; set; }
        public bool chipImplantado { get; set; }
        public string estadoAtencion { get; set; }
        public string motivoImplantacion { get; set; }
    
        public virtual ICollection<ACI_Chip_OrdenAtencion> ACI_Chip_OrdenAtencion { get; set; }
        public virtual ACI_Paciente ACI_Paciente { get; set; }
    }
}
