//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_Web.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACI_Paciente
    {
        public ACI_Paciente()
        {
            this.ACI_OrdenAtencion = new HashSet<ACI_OrdenAtencion>();
        }
    
        public int idPaciente { get; set; }
        public int idCliente { get; set; }
        public string nombrePaciente { get; set; }
        public System.DateTime fechaNacimientoPaciente { get; set; }
        public string tipoPaciente { get; set; }
        public string razaPaciente { get; set; }
        public int edadPaciente { get; set; }
    
        public virtual ACI_Cliente ACI_Cliente { get; set; }
        public virtual ICollection<ACI_OrdenAtencion> ACI_OrdenAtencion { get; set; }
    }
}
