//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_Web.Models.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACI_ModelConection : DbContext
    {
        public ACI_ModelConection()
            : base("name=ACI_ModelConection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACI_Chip> ACI_Chip { get; set; }
        public DbSet<ACI_Chip_OrdenAtencion> ACI_Chip_OrdenAtencion { get; set; }
        public DbSet<ACI_Cliente> ACI_Cliente { get; set; }
        public DbSet<ACI_OrdenAtencion> ACI_OrdenAtencion { get; set; }
        public DbSet<ACI_Paciente> ACI_Paciente { get; set; }
    }
}
