//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACI_Web.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACI_Chip
    {
        public ACI_Chip()
        {
            this.ACI_Chip_OrdenAtencion = new HashSet<ACI_Chip_OrdenAtencion>();
        }
    
        public int idChip { get; set; }
        public string nombreChip { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<ACI_Chip_OrdenAtencion> ACI_Chip_OrdenAtencion { get; set; }
    }
}
